In [1]:
import numpy as np
import pandas as pd

In [3]:
pd.set_option("display.max_rows", 6)

In [ ]:
registry = pd.read_excel("Registry.xlsx")

In [ ]:
registry

In [5]:
registry.drop(columns="Единый реестр субъектов малого и среднего предпринимательства по состоянию на 15.04.2024", inplace=True)
registry.drop(0, inplace=True)

In [6]:
dic = {}
old = registry.keys()
new = registry.iloc[0].values
for i in range(len(old)): dic[old[i]] = new[i]
registry.rename(columns=dic, inplace=True)

#удаляем исходную строку с заголовками столбцов
registry = registry.drop(1).reset_index().drop(columns="index")

In [ ]:
registry.drop(
    columns=["Производство инновационной, высокотехнологичной продукции",
        "Дата исключения из реестра", "Вновь созданный",
        "Наличие заключенных договоров, контрактов",
        "Участие в программах партнерства", "ОГРН",
        "Район", "Телефон", "E-mail", "WWW",
        "Является социальным предприятием", 
        "Основной вид деятельности"
    ], inplace=True)

In [10]:
registry.sample(3)

,Unnamed: 0,Наименование / ФИО,Тип субъекта,Категория,ОГРН,ИНН,Основной вид деятельности,Регион,Город,Населенный пункт,Вновь созданный,Дата включения в реестр,Дата исключения из реестра,Наличие лицензий,"Наличие заключенных договоров, контрактов",Участие в программах партнерства,Является социальным предприятием,Среднесписочная численность работников за предшествующий календарный год
3413,3413,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""МСО-36""",Юридическое лицо,Малое предприятие,1217700266190,7708396313,41.20 Строительство жилых и нежилых зданий,77 - г.Москва,NaN,NaN,Нет,10.07.2021,NaN,Нет,Нет,Нет,Нет,10.0
8324,8324,ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ КОРПО...,Юридическое лицо,Малое предприятие,1022601963999,2636036863,41.20 Строительство жилых и нежилых зданий,26 - Ставропольский край,г Ставрополь,NaN,Нет,01.08.2016,NaN,Нет,Нет,Нет,Нет,19.0
2451,2451,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""КАПИ...",Юридическое лицо,Малое предприятие,5177746152491,9701093264,41.20 Строительство жилых и нежилых зданий,77 - г.Москва,NaN,NaN,Нет,10.04.2024,NaN,Нет,Нет,Нет,Нет,NaN

In [1]:

# ------------------------------------------------ #
company = "Наименование / ФИО"
typeof_subject  = "Тип субъекта"
typeof_activity = "Основной вид деятельности"
category = "Категория"
ogrn = "ОГРН"
enn  = "ИНН"

# ------------------------------------------------ #
legal_entity = "Юридическое лицо"
construction = "41.20 Строительство жилых и нежилых зданий"
small_business  = 'Малое предприятие'
medium_business = 'Среднее предприятие'

In [10]:
mask = (registry[typeof_subject] == legal_entity) & (registry[typeof_activity] == construction) & ((registry[category] == small_business) | (registry[category] == medium_business))
registry = registry[mask].reset_index().drop(columns="index")
registry

,Наименование / ФИО,Тип субъекта,Категория,ОГРН,ИНН,Основной вид деятельности,Регион,Город,Населенный пункт,Вновь созданный,Дата включения в реестр,Дата исключения из реестра,Наличие лицензий,"Наличие заключенных договоров, контрактов",Участие в программах партнерства,Является социальным предприятием,Среднесписочная численность работников за предшествующий календарный год
0,"""КОРПОРАЦИЯ ВИТ"" (ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕ...",Юридическое лицо,Малое предприятие,1025004907080,5038038838,41.20 Строительство жилых и нежилых зданий,50 - Московская область,NaN,NaN,Нет,01.08.2016,NaN,Нет,Нет,Нет,Нет,36
1,"""ХОЗРАСЧЕТНАЯ СТРОИТЕЛЬНО-ТЕХНОЛОГИЧЕСКАЯ ФИРМ...",Юридическое лицо,Среднее предприятие,1025007270551,5027006369,41.20 Строительство жилых и нежилых зданий,50 - Московская область,г Дзержинский,NaN,Нет,01.08.2016,NaN,Да,Нет,Нет,Нет,201
2,"АКЦИОНЕРНОЕ ОБЩЕСТВО ""777""",Юридическое лицо,Малое предприятие,1021400692048,1414006922,41.20 Строительство жилых и нежилых зданий,77 - г.Москва,NaN,NaN,Нет,10.08.2017,NaN,Да,Нет,Нет,Нет,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8924,СОВМЕСТНОЕ ПРЕДПРИЯТИЕ ОБЩЕСТВО С ОГРАНИЧЕННОЙ...,Юридическое лицо,Среднее предприятие,1026500785673,6504043928,41.20 Строительство жилых и нежилых зданий,65 - Сахалинская область,г Корсаков,NaN,Нет,01.08.2016,NaN,Да,Нет,Нет,Нет,145
8925,"ФИРМА ""ТЕПЛОСТРОЙПРОЕКТ-С"" ОБЩЕСТВО С ОГРАНИЧЕ...",Юридическое лицо,Малое предприятие,1032000400233,2002001476,41.20 Строительство жилых и нежилых зданий,20 - Чеченская Республика,NaN,с Валерик,Нет,01.08.2016,NaN,Да,Нет,Нет,Нет,67
8926,"ФИРМА ""Ц.М.ХОЛДИНГ"" ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТ...",Юридическое лицо,Малое предприятие,1020700539640,0702005585,41.20 Строительство жилых и нежилых зданий,07 - Кабардино-Балкарская Республика,NaN,с Малка,Нет,01.08.2016,NaN,Нет,Нет,Нет,Нет,11